// Generated by scripts/api-schemas.mjs from packages/api-types/src/index.ts.
// Do not edit: run `npm run api-schemas`. A test fails when this is stale.
//
// Committed rather than generated at boot so the server never loads the
// TypeScript compiler to answer a request for its own documentation.

export const SCHEMAS: Record<string, any> = {
  "Role": {
    "description": "Contracts shared between the server and its clients. This package is the single source of truth for the shape of the data. The first-party front end imports it the way any third party would import the OpenAPI spec — it gets no privilege from doing so.",
    "type": "string",
    "enum": [
      "admin",
      "user",
      "guest"
    ]
  },
  "Capability": {
    "description": "What a role may do. Ask the server rather than deriving it from the name.",
    "type": "string",
    "enum": [
      "admin",
      "write",
      "curate",
      "play"
    ]
  },
  "Account": {
    "type": "object",
    "properties": {
      "id": {
        "type": "string"
      },
      "username": {
        "type": "string"
      },
      "role": {
        "$ref": "#/components/schemas/Role"
      },
      "subsonic": {
        "type": "number",
        "enum": [
          0,
          1
        ],
        "description": "Whether a recoverable password is stored for Subsonic clients."
      },
      "createdAt": {
        "type": "number"
      },
      "lastSeenAt": {
        "type": "number",
        "nullable": true
      }
    },
    "required": [
      "id",
      "username",
      "role",
      "subsonic",
      "createdAt",
      "lastSeenAt"
    ]
  },
  "TrackKind": {
    "type": "string",
    "enum": [
      "music",
      "audiobook",
      "podcast"
    ]
  },
  "Rendition": {
    "description": "One playable file of a track. A track is the song; a rendition is a file of it. The same music can exist as FLAC for listening and AAC for an iPod, and that is one library entry rather than two — a device that takes AAC and a browser that wants Opus are asking for the same song.",
    "type": "object",
    "properties": {
      "id": {
        "type": "string"
      },
      "format": {
        "type": "string"
      },
      "bitRate": {
        "type": "number"
      },
      "sampleRate": {
        "type": "number"
      },
      "channels": {
        "type": "number"
      },
      "size": {
        "type": "number"
      },
      "lossless": {
        "type": "number",
        "enum": [
          0,
          1
        ]
      },
      "preferred": {
        "type": "number",
        "enum": [
          0,
          1
        ],
        "description": "Exactly one per track: what a player gets and what a listing shows."
      },
      "path": {
        "type": "string"
      },
      "sourceId": {
        "type": "string"
      }
    },
    "required": [
      "id",
      "format",
      "bitRate",
      "sampleRate",
      "channels",
      "size",
      "lossless",
      "preferred",
      "path",
      "sourceId"
    ]
  },
  "Track": {
    "type": "object",
    "properties": {
      "id": {
        "type": "string"
      },
      "sourceId": {
        "type": "string"
      },
      "path": {
        "type": "string"
      },
      "kind": {
        "$ref": "#/components/schemas/TrackKind"
      },
      "name": {
        "type": "string"
      },
      "artist": {
        "type": "string"
      },
      "albumArtist": {
        "type": "string"
      },
      "album": {
        "type": "string"
      },
      "genre": {
        "type": "string"
      },
      "composer": {
        "type": "string"
      },
      "year": {
        "type": "number"
      },
      "trackNumber": {
        "type": "number"
      },
      "trackCount": {
        "type": "number"
      },
      "discNumber": {
        "type": "number"
      },
      "duration": {
        "type": "number",
        "description": "Seconds. Named `duration`, not `time`: it is a length, not a moment."
      },
      "bitRate": {
        "type": "number"
      },
      "sampleRate": {
        "type": "number"
      },
      "format": {
        "type": "string"
      },
      "size": {
        "type": "number"
      },
      "rating": {
        "type": "number"
      },
      "loved": {
        "type": "boolean"
      },
      "enabled": {
        "type": "boolean",
        "description": "The iTunes checkbox: does this track play in this list?"
      },
      "comments": {
        "type": "string"
      },
      "grouping": {
        "type": "string"
      },
      "bpm": {
        "type": "number"
      },
      "compilation": {
        "type": "boolean"
      },
      "playCount": {
        "type": "number"
      },
      "skipCount": {
        "type": "number"
      },
      "dateAdded": {
        "type": "number"
      },
      "lastPlayed": {
        "type": "number",
        "nullable": true
      },
      "artwork": {
        "type": "string",
        "nullable": true
      },
      "devices": {
        "type": "array",
        "items": {
          "type": "string"
        },
        "description": "Ids of the devices holding this track. Delivered with the page."
      },
      "tags": {
        "type": "array",
        "items": {
          "type": "string"
        },
        "description": "Tags the listener wrote, delivered with the page. Not the tags in the file: `genre`, `grouping` and `comments` are the file's own fields and are written back to disk. These are this library's opinion of the track and stay in the database, so a rescan cannot lose them and no audio file is rewritten to hold one."
      },
      "renditions": {
        "type": "array",
        "items": {
          "$ref": "#/components/schemas/Rendition"
        },
        "description": "Every file of this track, preferred first. Delivered with the page. The flat `format`, `size` and `bitRate` above are the preferred one's, so a client that does not care about renditions never has to look here."
      },
      "rev": {
        "type": "number"
      }
    },
    "required": [
      "id",
      "sourceId",
      "path",
      "kind",
      "name",
      "artist",
      "albumArtist",
      "album",
      "genre",
      "composer",
      "year",
      "trackNumber",
      "trackCount",
      "discNumber",
      "duration",
      "bitRate",
      "sampleRate",
      "format",
      "size",
      "rating",
      "loved",
      "enabled",
      "comments",
      "grouping",
      "bpm",
      "compilation",
      "playCount",
      "skipCount",
      "dateAdded",
      "lastPlayed",
      "artwork",
      "devices",
      "tags",
      "renditions",
      "rev"
    ]
  },
  "TrackPatch": {
    "description": "The fields a client is allowed to change.",
    "type": "object",
    "properties": {
      "name": {
        "type": "string"
      },
      "artist": {
        "type": "string"
      },
      "albumArtist": {
        "type": "string"
      },
      "album": {
        "type": "string"
      },
      "genre": {
        "type": "string"
      },
      "composer": {
        "type": "string"
      },
      "year": {
        "type": "number"
      },
      "trackNumber": {
        "type": "number"
      },
      "discNumber": {
        "type": "number"
      },
      "bpm": {
        "type": "number"
      },
      "comments": {
        "type": "string"
      },
      "grouping": {
        "type": "string"
      },
      "rating": {
        "type": "number"
      },
      "loved": {
        "type": "boolean"
      },
      "enabled": {
        "type": "boolean",
        "description": "The iTunes checkbox: does this track play in this list?"
      },
      "compilation": {
        "type": "boolean"
      },
      "kind": {
        "$ref": "#/components/schemas/TrackKind"
      }
    }
  },
  "SmartRule": {
    "type": "object",
    "properties": {
      "field": {
        "type": "string",
        "enum": [
          "rating",
          "playCount",
          "year",
          "genre",
          "artist",
          "albumArtist",
          "album",
          "dateAdded",
          "lastPlayed",
          "kind",
          "duration",
          "bpm",
          "tag"
        ],
        "description": "`tag` is the only one that is not a column: tags live one row per pair, so a tag rule is an EXISTS. `isNot` on it means \"not tagged this\", never \"tagged something else\" — a track with two tags is not the second answer."
      },
      "op": {
        "type": "string",
        "enum": [
          "is",
          "isNot",
          "contains",
          "gte",
          "lte",
          "inLastDays",
          "isSet",
          "isNotSet"
        ]
      },
      "value": {
        "oneOf": [
          {
            "type": "string"
          },
          {
            "type": "number"
          }
        ]
      }
    },
    "required": [
      "field",
      "op"
    ]
  },
  "SmartRules": {
    "type": "object",
    "properties": {
      "all": {
        "type": "array",
        "items": {
          "$ref": "#/components/schemas/SmartRule"
        }
      },
      "any": {
        "type": "array",
        "items": {
          "$ref": "#/components/schemas/SmartRule"
        }
      },
      "sort": {
        "type": "string"
      },
      "limit": {
        "type": "number"
      }
    }
  },
  "Playlist": {
    "type": "object",
    "properties": {
      "id": {
        "type": "string"
      },
      "name": {
        "type": "string"
      },
      "smart": {
        "type": "string",
        "nullable": true,
        "description": "Non-null = smart playlist: its contents are a query, not a list."
      },
      "rules": {
        "$ref": "#/components/schemas/SmartRules",
        "nullable": true
      },
      "trackCount": {
        "type": "number"
      },
      "createdAt": {
        "type": "number"
      },
      "rev": {
        "type": "number"
      }
    },
    "required": [
      "id",
      "name",
      "smart",
      "rules",
      "trackCount",
      "createdAt",
      "rev"
    ]
  },
  "Source": {
    "type": "object",
    "properties": {
      "id": {
        "type": "string"
      },
      "kind": {
        "type": "string",
        "enum": [
          "local",
          "rclone",
          "plex",
          "emby",
          "jellyfin"
        ]
      },
      "name": {
        "type": "string"
      },
      "root": {
        "type": "string"
      },
      "writable": {
        "type": "number",
        "enum": [
          0,
          1
        ],
        "description": "Write capability, denied by default. Without it, no file is ever touched."
      },
      "lastScanAt": {
        "type": "number",
        "nullable": true
      },
      "rev": {
        "type": "number"
      },
      "config": {
        "type": "object",
        "additionalProperties": {},
        "description": "What the source needs beyond its root — a daemon URL, a library id. Credentials are **not** here; see `secrets`."
      },
      "secrets": {
        "type": "array",
        "items": {
          "type": "string"
        },
        "description": "The names of the settings that are set and withheld: a token, a password. Enough for an interface to offer to replace one without ever reading it."
      },
      "mount": {
        "type": "object",
        "properties": {
          "device": {
            "type": "string"
          },
          "type": {
            "type": "string"
          },
          "network": {
            "type": "boolean"
          },
          "readOnly": {
            "type": "boolean"
          },
          "point": {
            "type": "string"
          }
        },
        "required": [
          "device",
          "type",
          "network",
          "readOnly",
          "point"
        ],
        "nullable": true,
        "description": "What the sources route adds for a local source: the disk its root sits on, or `null` when that disk is not mounted right now. Absent for the kinds that have no disk to be on."
      }
    },
    "required": [
      "id",
      "kind",
      "name",
      "root",
      "writable",
      "lastScanAt",
      "rev"
    ]
  },
  "JobKind": {
    "type": "string",
    "enum": [
      "scan",
      "transcode",
      "fingerprint",
      "podcast",
      "writeback",
      "sync",
      "acquire",
      "analyze",
      "relay",
      "move",
      "backup"
    ]
  },
  "JobState": {
    "type": "string",
    "enum": [
      "queued",
      "running",
      "paused",
      "done",
      "failed",
      "cancelled"
    ]
  },
  "Job": {
    "description": "Public view of a job: aggregates. Per-item detail is paginated separately.",
    "type": "object",
    "properties": {
      "id": {
        "type": "string"
      },
      "kind": {
        "$ref": "#/components/schemas/JobKind"
      },
      "state": {
        "$ref": "#/components/schemas/JobState"
      },
      "progress": {
        "type": "object",
        "properties": {
          "done": {
            "type": "number"
          },
          "total": {
            "type": "number"
          },
          "bytes": {
            "type": "number"
          }
        },
        "required": [
          "done",
          "total",
          "bytes"
        ]
      },
      "error": {
        "type": "string",
        "nullable": true
      },
      "createdAt": {
        "type": "number"
      },
      "startedAt": {
        "type": "number",
        "nullable": true
      },
      "finishedAt": {
        "type": "number",
        "nullable": true
      }
    },
    "required": [
      "id",
      "kind",
      "state",
      "progress",
      "error",
      "createdAt",
      "startedAt",
      "finishedAt"
    ]
  },
  "DeviceKind": {
    "type": "string",
    "enum": [
      "ipod-classic",
      "ipod-nano",
      "ipod-shuffle",
      "iphone",
      "ipad"
    ]
  },
  "Device": {
    "type": "object",
    "properties": {
      "id": {
        "type": "string"
      },
      "satelliteId": {
        "type": "string",
        "nullable": true
      },
      "name": {
        "type": "string"
      },
      "kind": {
        "$ref": "#/components/schemas/DeviceKind"
      },
      "model": {
        "type": "string"
      },
      "serial": {
        "type": "string"
      },
      "firmware": {
        "type": "string"
      },
      "capacity": {
        "type": "number"
      },
      "used": {
        "type": "object",
        "properties": {
          "audio": {
            "type": "number"
          },
          "video": {
            "type": "number"
          },
          "photos": {
            "type": "number"
          },
          "apps": {
            "type": "number"
          },
          "other": {
            "type": "number"
          }
        },
        "required": [
          "audio",
          "video",
          "photos",
          "apps",
          "other"
        ]
      },
      "battery": {
        "type": "number",
        "nullable": true
      },
      "acceptedFormats": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "autoSync": {
        "type": "number",
        "enum": [
          0,
          1
        ]
      },
      "syncMode": {
        "type": "string",
        "enum": [
          "all",
          "playlists"
        ]
      },
      "syncPlaylistIds": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "charging": {
        "type": "boolean"
      },
      "connected": {
        "type": "number",
        "enum": [
          0,
          1
        ]
      },
      "lastSync": {
        "type": "number",
        "nullable": true
      },
      "lastBackup": {
        "type": "number",
        "nullable": true
      }
    },
    "required": [
      "id",
      "satelliteId",
      "name",
      "kind",
      "model",
      "serial",
      "firmware",
      "capacity",
      "used",
      "battery",
      "acceptedFormats",
      "autoSync",
      "syncMode",
      "syncPlaylistIds",
      "charging",
      "connected",
      "lastSync",
      "lastBackup"
    ]
  },
  "DeviceTrack": {
    "description": "A track as it actually exists on the device.",
    "type": "object",
    "properties": {
      "deviceLocalId": {
        "type": "string"
      },
      "libraryTrackId": {
        "type": "string",
        "nullable": true,
        "description": "`null` = on the device but not in the library. Importable."
      },
      "name": {
        "type": "string"
      },
      "artist": {
        "type": "string"
      },
      "album": {
        "type": "string"
      },
      "duration": {
        "type": "number"
      },
      "size": {
        "type": "number"
      },
      "format": {
        "type": "string"
      },
      "sourceUrl": {
        "type": "string",
        "nullable": true,
        "description": "Where the satellite will serve the bytes. Null means it cannot be imported."
      },
      "syncedAt": {
        "type": "number",
        "nullable": true
      }
    },
    "required": [
      "deviceLocalId",
      "libraryTrackId",
      "name",
      "artist",
      "album",
      "duration",
      "size",
      "format",
      "sourceUrl",
      "syncedAt"
    ]
  },
  "SyncPlan": {
    "description": "What a sync would do. Returned by `POST /devices/:id/sync` with `dryRun`.",
    "type": "object",
    "properties": {
      "add": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "trackId": {
              "type": "string"
            },
            "name": {
              "type": "string"
            },
            "artist": {
              "type": "string"
            },
            "size": {
              "type": "number"
            },
            "transcode": {
              "type": "string",
              "nullable": true
            }
          },
          "required": [
            "trackId",
            "name",
            "artist",
            "size",
            "transcode"
          ]
        }
      },
      "remove": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "deviceLocalId": {
              "type": "string"
            },
            "name": {
              "type": "string"
            },
            "size": {
              "type": "number"
            }
          },
          "required": [
            "deviceLocalId",
            "name",
            "size"
          ]
        }
      },
      "keep": {
        "type": "number"
      },
      "bytesAdded": {
        "type": "number"
      },
      "bytesFreed": {
        "type": "number"
      },
      "free": {
        "type": "number"
      },
      "shortBy": {
        "type": "number",
        "nullable": true,
        "description": "Non-null when the plan does not fit: how many bytes short it is."
      }
    },
    "required": [
      "add",
      "remove",
      "keep",
      "bytesAdded",
      "bytesFreed",
      "free",
      "shortBy"
    ]
  },
  "JobItemState": {
    "description": "One unit of work inside a job — a track written, fetched or refused.",
    "type": "string",
    "enum": [
      "pending",
      "done",
      "failed",
      "skipped"
    ]
  },
  "JobItem": {
    "type": "object",
    "properties": {
      "idx": {
        "type": "number"
      },
      "ref": {
        "type": "string"
      },
      "state": {
        "$ref": "#/components/schemas/JobItemState"
      },
      "bytes": {
        "type": "number"
      },
      "error": {
        "type": "string",
        "nullable": true
      }
    },
    "required": [
      "idx",
      "ref",
      "state",
      "bytes",
      "error"
    ]
  },
  "JobItemsPage": {
    "description": "A page of job items, with totals over the *whole* job. Counting the page would answer \"3 of the 200 shown\" when the question is \"3 of 40000\".",
    "type": "object",
    "properties": {
      "items": {
        "type": "array",
        "items": {
          "$ref": "#/components/schemas/JobItem"
        }
      },
      "next": {
        "type": "string",
        "nullable": true
      },
      "counts": {
        "type": "object",
        "additionalProperties": {
          "type": "number"
        }
      }
    },
    "required": [
      "items",
      "next",
      "counts"
    ]
  },
  "DeviceStats": {
    "type": "object",
    "properties": {
      "tracks": {
        "type": "number"
      },
      "orphans": {
        "type": "number"
      },
      "bytes": {
        "type": "number"
      },
      "seconds": {
        "type": "number"
      }
    },
    "required": [
      "tracks",
      "orphans",
      "bytes",
      "seconds"
    ]
  },
  "WantResult": {
    "description": "The outcome of hand-picking tracks for a device. Split three ways because a drop of 200 tracks onto an iPod that already holds 180 of them should say so, rather than claim it added 200.",
    "type": "object",
    "properties": {
      "added": {
        "type": "number"
      },
      "alreadyWanted": {
        "type": "number"
      },
      "unknown": {
        "type": "number"
      }
    },
    "required": [
      "added",
      "alreadyWanted",
      "unknown"
    ]
  },
  "Schedule": {
    "description": "A recurring job. The cron expression is stored as written, not as a computed next-fire time: that is what makes a schedule mean the same thing across a restart and across a DST boundary.",
    "type": "object",
    "properties": {
      "id": {
        "type": "string"
      },
      "name": {
        "type": "string"
      },
      "cron": {
        "type": "string",
        "description": "Five fields, local time: minute hour day-of-month month day-of-week."
      },
      "kind": {
        "$ref": "#/components/schemas/JobKind"
      },
      "payload": {},
      "enabled": {
        "type": "number",
        "enum": [
          0,
          1
        ]
      },
      "lastRunAt": {
        "type": "number",
        "nullable": true
      },
      "lastRunKey": {
        "type": "string",
        "nullable": true,
        "description": "Local wall-clock minute of the last run — the identity of an occurrence."
      },
      "lastJobId": {
        "type": "string",
        "nullable": true
      }
    },
    "required": [
      "id",
      "name",
      "cron",
      "kind",
      "payload",
      "enabled",
      "lastRunAt",
      "lastRunKey",
      "lastJobId"
    ]
  },
  "Radio": {
    "type": "object",
    "properties": {
      "id": {
        "type": "string"
      },
      "name": {
        "type": "string"
      },
      "streamUrl": {
        "type": "string"
      },
      "homepageUrl": {
        "type": "string",
        "nullable": true
      },
      "imageUrl": {
        "type": "string",
        "nullable": true
      },
      "genre": {
        "type": "string"
      },
      "country": {
        "type": "string"
      },
      "bitrate": {
        "type": "number"
      },
      "codec": {
        "type": "string"
      },
      "favorite": {
        "type": "number",
        "enum": [
          0,
          1
        ]
      }
    },
    "required": [
      "id",
      "name",
      "streamUrl",
      "homepageUrl",
      "imageUrl",
      "genre",
      "country",
      "bitrate",
      "codec",
      "favorite"
    ]
  },
  "Podcast": {
    "type": "object",
    "properties": {
      "id": {
        "type": "string"
      },
      "feedUrl": {
        "type": "string"
      },
      "title": {
        "type": "string"
      },
      "description": {
        "type": "string"
      },
      "author": {
        "type": "string"
      },
      "imageUrl": {
        "type": "string",
        "nullable": true
      },
      "siteUrl": {
        "type": "string",
        "nullable": true
      },
      "cron": {
        "type": "string",
        "nullable": true,
        "description": "Per-feed refresh. `null` means manual only."
      },
      "keepLast": {
        "type": "number",
        "description": "Newest N downloaded episodes kept on disk. 0 keeps every one."
      },
      "autoDownload": {
        "type": "number",
        "enum": [
          0,
          1
        ]
      },
      "targetSourceId": {
        "type": "string",
        "nullable": true
      },
      "targetPath": {
        "type": "string"
      },
      "lastFetchAt": {
        "type": "number",
        "nullable": true
      },
      "lastError": {
        "type": "string",
        "nullable": true,
        "description": "Why the last refresh failed. A feed dead for a month should say so."
      },
      "episodeCount": {
        "type": "number"
      },
      "downloadedCount": {
        "type": "number"
      }
    },
    "required": [
      "id",
      "feedUrl",
      "title",
      "description",
      "author",
      "imageUrl",
      "siteUrl",
      "cron",
      "keepLast",
      "autoDownload",
      "targetSourceId",
      "targetPath",
      "lastFetchAt",
      "lastError",
      "episodeCount",
      "downloadedCount"
    ]
  },
  "Episode": {
    "type": "object",
    "properties": {
      "id": {
        "type": "string"
      },
      "podcastId": {
        "type": "string"
      },
      "guid": {
        "type": "string",
        "description": "The feed's identity for this episode. Never the URL — those get rewritten."
      },
      "title": {
        "type": "string"
      }
    },
    "required": [
      "id",
      "podcastId",
      "guid",
      "title"
    ]
  },
  "RadioHit": {
    "description": "A station proposed by the community directory, not yet in the library. Everything needed to create a `Radio` from it without probing the stream.",
    "type": "object",
    "properties": {
      "name": {
        "type": "string"
      },
      "streamUrl": {
        "type": "string"
      },
      "homepageUrl": {
        "type": "string",
        "nullable": true
      },
      "imageUrl": {
        "type": "string",
        "nullable": true
      },
      "genre": {
        "type": "string"
      },
      "country": {
        "type": "string"
      },
      "bitrate": {
        "type": "number"
      },
      "codec": {
        "type": "string"
      },
      "votes": {
        "type": "number",
        "description": "Community votes — what proposals are ranked by."
      }
    },
    "required": [
      "name",
      "streamUrl",
      "homepageUrl",
      "imageUrl",
      "genre",
      "country",
      "bitrate",
      "codec",
      "votes"
    ]
  },
  "OrganizePlan": {
    "description": "What a reorganisation would do. Returned by `POST /organize` without `apply`, which is the default — the one operation that rewrites a disk is never a single click.",
    "type": "object",
    "properties": {
      "moves": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "trackId": {
              "type": "string"
            },
            "from": {
              "type": "string"
            },
            "to": {
              "type": "string"
            }
          },
          "required": [
            "trackId",
            "from",
            "to"
          ]
        }
      },
      "conflicts": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "to": {
              "type": "string"
            },
            "trackIds": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          },
          "required": [
            "to",
            "trackIds"
          ]
        },
        "description": "Destinations two or more tracks both want. Nothing runs while any exist."
      },
      "unchanged": {
        "type": "number"
      },
      "skipped": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "trackId": {
              "type": "string"
            },
            "reason": {
              "type": "string"
            }
          },
          "required": [
            "trackId",
            "reason"
          ]
        },
        "description": "Tracks the pattern could not render, and which field was empty."
      }
    },
    "required": [
      "moves",
      "conflicts",
      "unchanged",
      "skipped"
    ]
  },
  "Move": {
    "description": "One file a reorganisation moved. The log, and what makes undo possible.",
    "type": "object",
    "properties": {
      "id": {
        "type": "number"
      },
      "jobId": {
        "type": "string"
      },
      "trackId": {
        "type": "string"
      },
      "sourceId": {
        "type": "string"
      },
      "fromPath": {
        "type": "string"
      },
      "toPath": {
        "type": "string"
      },
      "movedAt": {
        "type": "number"
      },
      "undoneAt": {
        "type": "number",
        "nullable": true
      }
    },
    "required": [
      "id",
      "jobId",
      "trackId",
      "sourceId",
      "fromPath",
      "toPath",
      "movedAt",
      "undoneAt"
    ]
  },
  "StoreEntry": {
    "description": "A plugin as a store index advertises it. `installable` is false when this host is too old or too new for it, with the reason — better said before the install than after it fails.",
    "type": "object",
    "properties": {
      "id": {
        "type": "string"
      },
      "name": {
        "type": "string"
      },
      "version": {
        "type": "string"
      },
      "description": {
        "type": "string"
      },
      "author": {
        "type": "string"
      },
      "homepage": {
        "type": "string"
      },
      "hostApi": {
        "type": "string"
      },
      "tarball": {
        "type": "string"
      },
      "sha256": {
        "type": "string",
        "description": "Checked when present: an index over HTTPS cannot vouch for bytes elsewhere."
      },
      "permissions": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "installable": {
        "type": "boolean"
      },
      "reason": {
        "type": "string"
      }
    },
    "required": [
      "id",
      "name",
      "version",
      "hostApi",
      "tarball",
      "installable"
    ]
  },
  "DuplicateGroup": {
    "description": "Rows that look like one song. Proposed, never merged automatically — two different songs sharing a title is ordinary, and a wrong merge loses a recording.",
    "type": "object",
    "properties": {
      "keeperId": {
        "type": "string",
        "description": "Suggested keeper: the copy carrying plays and a rating, which cannot be recovered."
      },
      "reason": {
        "type": "string",
        "enum": [
          "fingerprint",
          "metadata"
        ],
        "description": "`fingerprint` compared the audio; `metadata` compared tags and length."
      },
      "tracks": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "id": {
              "type": "string"
            },
            "name": {
              "type": "string"
            },
            "artist": {
              "type": "string"
            },
            "album": {
              "type": "string"
            },
            "duration": {
              "type": "number"
            },
            "format": {
              "type": "string"
            },
            "size": {
              "type": "number"
            },
            "bitRate": {
              "type": "number"
            },
            "rating": {
              "type": "number"
            },
            "playCount": {
              "type": "number"
            },
            "renditions": {
              "type": "number"
            }
          },
          "required": [
            "id",
            "name",
            "artist",
            "album",
            "duration",
            "format",
            "size",
            "bitRate",
            "rating",
            "playCount",
            "renditions"
          ]
        }
      }
    },
    "required": [
      "keeperId",
      "reason",
      "tracks"
    ]
  },
  "CommandResult": {
    "description": "What a plugin command answers. A closed set, so a menu can act on the result without knowing anything about the plugin. `tracks` is separate from `playlist` because \"find me more like this\" produces a selection: forcing it into a playlist litters the sidebar with something the user then has to delete, and saving it should be their choice.",
    "oneOf": [
      {
        "type": "object",
        "properties": {
          "kind": {
            "type": "string",
            "const": "done"
          },
          "message": {
            "type": "string"
          }
        },
        "required": [
          "kind"
        ]
      },
      {
        "type": "object",
        "properties": {
          "kind": {
            "type": "string",
            "const": "job"
          },
          "job": {
            "$ref": "#/components/schemas/Job"
          }
        },
        "required": [
          "kind",
          "job"
        ]
      },
      {
        "type": "object",
        "properties": {
          "kind": {
            "type": "string",
            "const": "playlist"
          },
          "id": {
            "type": "string"
          },
          "name": {
            "type": "string"
          }
        },
        "required": [
          "kind",
          "id",
          "name"
        ]
      },
      {
        "type": "object",
        "properties": {
          "kind": {
            "type": "string",
            "const": "tracks"
          },
          "ids": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        },
        "required": [
          "kind",
          "ids"
        ]
      },
      {
        "type": "object",
        "properties": {
          "kind": {
            "type": "string",
            "const": "text"
          },
          "title": {
            "type": "string"
          },
          "body": {
            "type": "string"
          }
        },
        "required": [
          "kind",
          "body"
        ]
      },
      {
        "type": "object",
        "properties": {
          "kind": {
            "type": "string",
            "const": "suggestions"
          },
          "title": {
            "type": "string"
          },
          "items": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "name": {
                  "type": "string"
                },
                "artist": {
                  "type": "string"
                },
                "why": {
                  "type": "string"
                }
              },
              "required": [
                "name",
                "artist"
              ]
            }
          }
        },
        "required": [
          "kind",
          "items"
        ]
      }
    ]
  },
  "PluginState": {
    "type": "string",
    "enum": [
      "installed",
      "active",
      "failed",
      "disabled"
    ]
  },
  "Plugin": {
    "description": "An installed plugin. `permissions` are declared by the author and shown before install. They are not enforced: a plugin runs in the server's own process and can do anything the server can. That is the same bargain Home Assistant and Volumio make, and the UI should say so plainly rather than imply a sandbox that is not there.",
    "type": "object",
    "properties": {
      "id": {
        "type": "string"
      },
      "name": {
        "type": "string"
      },
      "version": {
        "type": "string"
      },
      "description": {
        "type": "string"
      },
      "author": {
        "type": "string"
      },
      "permissions": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "contributes": {
        "type": "object",
        "additionalProperties": {},
        "description": "Where the plugin asks to appear in the UI."
      },
      "enabled": {
        "type": "number",
        "enum": [
          0,
          1
        ]
      },
      "state": {
        "$ref": "#/components/schemas/PluginState"
      },
      "error": {
        "type": "string",
        "nullable": true,
        "description": "Why it is not running."
      },
      "config": {
        "type": "object",
        "additionalProperties": {}
      },
      "commands": {
        "type": "array",
        "items": {
          "type": "string"
        },
        "description": "What can be invoked right now — not the same as what `contributes` declares. An installed but stopped plugin contributes menu entries that cannot run, and the UI should be able to tell those apart."
      }
    },
    "required": [
      "id",
      "name",
      "version",
      "description",
      "author",
      "permissions",
      "contributes",
      "enabled",
      "state",
      "error",
      "config"
    ]
  },
  "Stats": {
    "description": "Library totals, computed in SQL over the whole library rather than a page.",
    "type": "object",
    "properties": {
      "tracks": {
        "type": "number"
      },
      "albums": {
        "type": "number"
      },
      "artists": {
        "type": "number"
      },
      "bytes": {
        "type": "number"
      },
      "seconds": {
        "type": "number"
      },
      "missing": {
        "type": "number"
      },
      "playlists": {
        "type": "number"
      },
      "podcasts": {
        "type": "number"
      },
      "radios": {
        "type": "number"
      },
      "sources": {
        "type": "number"
      },
      "devices": {
        "type": "number"
      },
      "jobs": {
        "type": "object",
        "additionalProperties": {
          "type": "number"
        }
      }
    },
    "required": [
      "tracks",
      "albums",
      "artists",
      "bytes",
      "seconds",
      "missing",
      "playlists",
      "podcasts",
      "radios",
      "sources",
      "devices",
      "jobs"
    ]
  },
  "RestoreReport": {
    "description": "What a restore did. It adds, never replaces, so most of it is counts of skips.",
    "type": "object",
    "properties": {
      "tracks": {
        "type": "object",
        "properties": {
          "matched": {
            "type": "number"
          },
          "missing": {
            "type": "number"
          }
        },
        "required": [
          "matched",
          "missing"
        ]
      },
      "playlists": {
        "type": "object",
        "properties": {
          "created": {
            "type": "number"
          },
          "skipped": {
            "type": "number"
          }
        },
        "required": [
          "created",
          "skipped"
        ]
      },
      "radios": {
        "type": "object",
        "properties": {
          "created": {
            "type": "number"
          },
          "skipped": {
            "type": "number"
          }
        },
        "required": [
          "created",
          "skipped"
        ]
      },
      "podcasts": {
        "type": "object",
        "properties": {
          "created": {
            "type": "number"
          },
          "skipped": {
            "type": "number"
          }
        },
        "required": [
          "created",
          "skipped"
        ]
      },
      "schedules": {
        "type": "object",
        "properties": {
          "created": {
            "type": "number"
          },
          "skipped": {
            "type": "number"
          }
        },
        "required": [
          "created",
          "skipped"
        ]
      },
      "devices": {
        "type": "object",
        "properties": {
          "updated": {
            "type": "number"
          }
        },
        "required": [
          "updated"
        ]
      }
    },
    "required": [
      "tracks",
      "playlists",
      "radios",
      "podcasts",
      "schedules",
      "devices"
    ]
  },
  "MissingTrack": {
    "description": "A track whose file the scanner could not find. Soft deleted, never removed.",
    "type": "object",
    "properties": {
      "id": {
        "type": "string"
      },
      "sourceId": {
        "type": "string"
      },
      "sourceName": {
        "type": "string"
      },
      "path": {
        "type": "string"
      },
      "name": {
        "type": "string"
      },
      "artist": {
        "type": "string"
      },
      "album": {
        "type": "string"
      },
      "duration": {
        "type": "number"
      },
      "rating": {
        "type": "number"
      },
      "playCount": {
        "type": "number"
      },
      "deletedAt": {
        "type": "number"
      }
    },
    "required": [
      "id",
      "sourceId",
      "sourceName",
      "path",
      "name",
      "artist",
      "album",
      "duration",
      "rating",
      "playCount",
      "deletedAt"
    ]
  },
  "Output": {
    "description": "Where the music comes out. `local` means the client that is asking.",
    "type": "object",
    "properties": {
      "id": {
        "type": "string"
      },
      "name": {
        "type": "string"
      },
      "kind": {
        "oneOf": [
          {
            "type": "string",
            "const": "upnp"
          },
          {
            "type": "string",
            "const": "airplay"
          },
          {
            "type": "string",
            "const": "cast"
          },
          {
            "type": "string",
            "const": "satellite"
          },
          {
            "allOf": [
              {
                "type": "string"
              },
              {
                "type": "object",
                "properties": {}
              }
            ]
          }
        ]
      },
      "manufacturer": {
        "type": "string"
      },
      "model": {
        "type": "string"
      },
      "address": {
        "type": "string"
      },
      "formats": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "stale": {
        "type": "boolean",
        "description": "Registered but silent for five minutes: probably unplugged, not gone."
      },
      "volume": {
        "type": "boolean",
        "description": "Whether a volume slider would do anything. AirPlay's volume is elsewhere."
      }
    },
    "required": [
      "id",
      "name",
      "kind",
      "manufacturer",
      "model",
      "address",
      "formats",
      "stale"
    ]
  },
  "PlayerTarget": {
    "oneOf": [
      {
        "type": "object",
        "properties": {
          "kind": {
            "type": "string",
            "const": "local"
          }
        },
        "required": [
          "kind"
        ]
      },
      {
        "type": "object",
        "properties": {
          "kind": {
            "type": "string",
            "const": "output"
          },
          "id": {
            "type": "string"
          },
          "name": {
            "type": "string"
          }
        },
        "required": [
          "kind",
          "id",
          "name"
        ]
      }
    ]
  },
  "PlayerState": {
    "description": "The shared queue. The server holds the intent — what is queued, which one is current, whether it should be playing, where. A renderer executes it and reports its position back. That separation is what makes controlling playback from one device while it comes out of another work at all.",
    "type": "object",
    "properties": {
      "queue": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "index": {
        "type": "number",
        "description": "Index into `queue`. -1 when nothing is loaded."
      },
      "trackId": {
        "type": "string",
        "nullable": true
      },
      "playing": {
        "type": "boolean"
      },
      "position": {
        "type": "number"
      },
      "target": {
        "$ref": "#/components/schemas/PlayerTarget"
      },
      "repeat": {
        "type": "string",
        "enum": [
          "off",
          "all",
          "one"
        ]
      },
      "shuffle": {
        "type": "boolean"
      },
      "revision": {
        "type": "number",
        "description": "Bumped on every change, so a client can tell its own echo from someone else's."
      },
      "by": {
        "type": "string",
        "nullable": true,
        "description": "Which controller last changed it, from the `x-jukebox-client` header."
      },
      "stream": {
        "$ref": "#/components/schemas/PlayerStream",
        "nullable": true,
        "description": "What is playing when it is not a library track — a radio station, a podcast episode still in its feed. Deliberately not `trackId`: those are URLs with a display name, not rows anything can look up, and every consumer of `trackId` gets to stay sure it names a track. Non-null wins over `trackId` as \"what is current\"; cleared the moment a queued track starts."
      }
    },
    "required": [
      "queue",
      "index",
      "trackId",
      "playing",
      "position",
      "target",
      "repeat",
      "shuffle",
      "revision",
      "by",
      "stream"
    ]
  },
  "PlayerStream": {
    "description": "The whole of what another client needs to show — and, if it was already audible, keep playing — something the library does not hold.",
    "type": "object",
    "properties": {
      "id": {
        "type": "string",
        "description": "`radio:<id>` or `ep:<id>`; the prefix is the kind."
      },
      "name": {
        "type": "string"
      },
      "artist": {
        "type": "string"
      },
      "album": {
        "type": "string"
      },
      "imageUrl": {
        "type": "string",
        "nullable": true
      },
      "src": {
        "type": "string",
        "description": "The stream itself, so a second window can play it, not just name it."
      },
      "duration": {
        "type": "number",
        "description": "Seconds; 0 for a station, which has no end."
      }
    },
    "required": [
      "id",
      "name",
      "artist",
      "album",
      "imageUrl",
      "src",
      "duration"
    ]
  },
  "Memberships": {
    "description": "Every playlist and device holding one track. Answered by the server because a client cannot: a smart playlist's membership is a query rather than a stored list, so anything computed client-side would be wrong for exactly the playlists people care most about.",
    "type": "object",
    "properties": {
      "playlists": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "id": {
              "type": "string"
            },
            "name": {
              "type": "string"
            },
            "smart": {
              "type": "string",
              "nullable": true
            },
            "position": {
              "type": "number",
              "nullable": true
            }
          },
          "required": [
            "id",
            "name",
            "smart",
            "position"
          ]
        },
        "description": "`position` is where it sits in a manual playlist, and null for a smart one."
      },
      "devices": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "id": {
              "type": "string"
            },
            "name": {
              "type": "string"
            },
            "wanted": {
              "type": "boolean"
            },
            "present": {
              "type": "boolean"
            }
          },
          "required": [
            "id",
            "name",
            "wanted",
            "present"
          ]
        },
        "description": "`present` is on the device now; `wanted` is picked but not yet synced."
      }
    },
    "required": [
      "playlists",
      "devices"
    ]
  },
  "TracksDelta": {
    "type": "object",
    "properties": {
      "revision": {
        "type": "number"
      },
      "changed": {
        "type": "array",
        "items": {
          "$ref": "#/components/schemas/Track"
        }
      },
      "deleted": {
        "type": "array",
        "items": {
          "type": "string"
        }
      }
    },
    "required": [
      "revision",
      "changed",
      "deleted"
    ]
  },
  "TrackQuery": {
    "type": "object",
    "properties": {
      "sort": {
        "type": "string",
        "enum": [
          "artist",
          "album",
          "name",
          "added",
          "-artist",
          "-album",
          "-name",
          "-added"
        ]
      },
      "cursor": {
        "type": "string"
      },
      "limit": {
        "type": "number"
      },
      "kind": {
        "$ref": "#/components/schemas/TrackKind"
      },
      "q": {
        "type": "string"
      },
      "genre": {
        "type": "string"
      },
      "artist": {
        "type": "string"
      },
      "album": {
        "type": "string"
      },
      "format": {
        "type": "string",
        "description": "Codec name, as the scanner stores it: `mp3`, `aac`, `alac`, `flac`, `opus`, `vorbis`, `wav`, `aiff`. Not a container — an `.m4a` is `aac` or `alac`, and an `.ogg` is `opus` or `vorbis`. Matched case-insensitively."
      },
      "tag": {
        "type": "string",
        "description": "Carries this tag. One at a time: a second one is a smart playlist."
      },
      "missing": {
        "type": "string",
        "enum": [
          "album",
          "artist",
          "albumartist",
          "genre",
          "year",
          "track",
          "any"
        ],
        "description": "Tracks with a field left empty, for consolidating a library. `any` is the union of the rest. Deliberately about *fields*, not about quality: a track with no year is incomplete, a track with a year you disagree with is not, and only the first is something a query can find. No `artwork`: the column exists but nothing writes it — covers are read on demand rather than during a scan, because opening a hundred thousand files for their artwork would make a first scan interminable. A filter on it would return the entire library while looking like it worked."
      },
      "folder": {
        "type": "string",
        "description": "Everything under a folder, matched on the stored path as a prefix. A path, not a name: two sources can both hold `Podcasts/`, and the whole point of pointing at a folder is that it is *that* one."
      },
      "sourceId": {
        "type": "string"
      },
      "rating": {
        "type": "number",
        "description": "Exactly this many stars, 0–5. `0` is \"never rated\", which is a real query."
      },
      "ratingMin": {
        "type": "number",
        "description": "This many stars or more. The one people actually want."
      },
      "lossless": {
        "type": "boolean",
        "description": "Whether the file that would play is a lossless one. Asked of the rendition rather than derived from the codec name, because \"is this a lossy copy\" is a property of the file and a client-side codec list rots."
      },
      "onDevice": {
        "type": "string",
        "description": "Present on these devices."
      },
      "notOnDevice": {
        "type": "string",
        "description": "Missing from these devices — \"what is left to sync\"."
      },
      "match": {
        "type": "string",
        "enum": [
          "any",
          "all"
        ],
        "description": "`all`: on every listed device. `any` by default."
      }
    }
  },
  "ApiError": {
    "type": "object",
    "properties": {
      "error": {
        "type": "object",
        "properties": {
          "code": {
            "type": "string"
          },
          "message": {
            "type": "string"
          },
          "details": {}
        },
        "required": [
          "code",
          "message"
        ]
      }
    },
    "required": [
      "error"
    ]
  }
}
